# Generated by Django 5.0.1 on 2024-02-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioEcuapass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=50, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='apellidos')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('es_director', models.BooleanField(default=False)),
                ('es_funcionario', models.BooleanField(default=False)),
                ('es_externo', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('nro_docs_creados', models.IntegerField(default=0)),
                ('nro_docs_asignados', models.IntegerField(default=0)),
                ('perfil', models.CharField(choices=[('externo', 'Externo'), ('funcionario', 'Funcionario'), ('director', 'Director')], max_length=20)),
                ('username', models.CharField(error_messages={'unique': 'Este nombre de usuario ya está registrado..'}, help_text='Requerido. Letras y digitos, sin espacios ni carácteres, tildes o eñes.', max_length=30, unique=True, verbose_name='nombre de usuario')),
                ('email', models.EmailField(error_messages={'unique': 'Este correo ya está registrado..'}, help_text='Requerido.', max_length=254, unique=True, verbose_name='correo electrónico')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
