# Generated by Django 5.0.1 on 2024-01-25 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifiesto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='certificado',
        ),
        migrations.AddField(
            model_name='manifiesto',
            name='remolque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='remolque', to='manifiesto.vehiculo'),
        ),
        migrations.AlterField(
            model_name='manifiesto',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehiculo', to='manifiesto.vehiculo'),
        ),
    ]
