# Generated by Django 5.0.1 on 2024-02-25 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appdocs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaporte',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartaporte',
            name='documento',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appdocs.cartaportedoc'),
        ),
        migrations.AddField(
            model_name='declaracion',
            name='cartaporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appdocs.cartaporte'),
        ),
        migrations.AddField(
            model_name='declaracion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='declaracion',
            name='documento',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appdocs.declaraciondoc'),
        ),
        migrations.AddField(
            model_name='cartaporte',
            name='remitente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appdocs.empresa'),
        ),
        migrations.AddField(
            model_name='manifiesto',
            name='cartaporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appdocs.cartaporte'),
        ),
        migrations.AddField(
            model_name='manifiesto',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manifiesto',
            name='documento',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appdocs.manifiestodoc'),
        ),
        migrations.AddField(
            model_name='manifiesto',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculo', to='appdocs.vehiculo'),
        ),
    ]
