# Generated by Django 5.0 on 2024-01-04 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartaporteDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('txt00', models.CharField(max_length=20)),
                ('txt01', models.CharField(max_length=200)),
                ('txt02', models.CharField(max_length=200)),
                ('txt03', models.CharField(max_length=200)),
                ('txt04', models.CharField(max_length=200)),
                ('txt05', models.CharField(max_length=200)),
                ('txt06', models.CharField(max_length=200)),
                ('txt07', models.CharField(max_length=200)),
                ('txt08', models.CharField(max_length=200)),
                ('txt09', models.CharField(max_length=200)),
                ('txt10', models.CharField(max_length=200)),
                ('txt11', models.CharField(max_length=200)),
                ('txt12', models.CharField(max_length=200)),
                ('txt13_1', models.CharField(max_length=200)),
                ('txt13_2', models.CharField(max_length=200)),
                ('txt14', models.CharField(max_length=200)),
                ('txt15', models.CharField(max_length=200)),
                ('txt16', models.CharField(max_length=200)),
                ('txt17_11', models.CharField(max_length=200)),
                ('txt17_12', models.CharField(max_length=200)),
                ('txt17_13', models.CharField(max_length=200)),
                ('txt17_14', models.CharField(max_length=200)),
                ('txt17_21', models.CharField(max_length=200)),
                ('txt17_22', models.CharField(max_length=200)),
                ('txt17_23', models.CharField(max_length=200)),
                ('txt17_24', models.CharField(max_length=200)),
                ('txt17_31', models.CharField(max_length=200)),
                ('txt17_32', models.CharField(max_length=200)),
                ('txt17_33', models.CharField(max_length=200)),
                ('txt17_34', models.CharField(max_length=200)),
                ('txt17_41', models.CharField(max_length=200)),
                ('txt17_42', models.CharField(max_length=200)),
                ('txt17_43', models.CharField(max_length=200)),
                ('txt17_44', models.CharField(max_length=200)),
                ('txt18', models.CharField(max_length=200)),
                ('txt19', models.CharField(max_length=200)),
                ('txt20', models.CharField(max_length=200)),
                ('txt21', models.CharField(max_length=200)),
                ('txt22', models.CharField(max_length=200)),
                ('txt23', models.CharField(max_length=200)),
                ('txt24', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direcccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=20)),
                ('tipoId', models.CharField(max_length=20)),
                ('identificador', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cartaporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='creador.cartaportedoc')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creador.empresa')),
            ],
        ),
    ]
