# Generated by Django 5.0 on 2024-01-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='identificador',
            new_name='numeroId',
        ),
    ]
