# Generated by Django 5.0 on 2024-01-11 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creador', '0002_rename_identificador_empresa_numeroid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaporte',
            name='remitente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creador.empresa'),
        ),
    ]
