# Generated by Django 5.0 on 2024-01-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creador', '0003_alter_cartaporte_remitente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='direcccion',
            new_name='direccion',
        ),
    ]
